---
title: "disease_map_sbc"
output:
  html_document: default
  pdf_document: default
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  include = TRUE,  cache = FALSE,  collapse = TRUE,  echo = TRUE,
  message = FALSE, tidy = FALSE,  warning = FALSE,   comment = "  ",
  dev = "png", dev.args = list(bg = '#FFFFF8'), dpi = 300,
  fig.align = "center",  fig.width = 7,  fig.asp = 0.618,  fig.show = "hold",
  out.width = "90%")
```


```{r}
library(ggplot2);
library(knitr); 
library(tidyverse);
library(rstan);
library(tufte);
library(parallel);
library(cmdstanr);
library(posterior);
library("bayesplot");
library("ggplot2");
library("rstanarm");
set_cmdstan_path("/Users/hyunjimoon/Dropbox/20_paper/charles/code/cmdstan")
options(digits = 2);  options(htmltools.dir.version = FALSE)
parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
scriptDir <- getwd()
modelDir <- file.path(scriptDir, "models")
dataDir <- file.path(scriptDir, "data")
nChains <- 4
parallel_chains <- min(nChains, detectCores())
set_Data_Model_Dir <- function(dataFile, modelName){
  scriptDir <- getwd()
  modelDir <- file.path(scriptDir, "models")
  dataDir <- file.path(scriptDir, "data")
  outDir <- file.path(scriptDir, "deliv", modelName)
  delivDir <- file.path("deliv", modelName)
  data <- read_rdump(file.path(dataDir, dataFile))
  file <- file.path(modelDir, modelName, paste0(modelName, ".stan"))
  mod <- cmdstan_model(file)
  return(list(data = data, mod = mod, delivDir = delivDir)) 
}
set_Model_Dir <- function(modelName){
  scriptDir <- getwd()
  modelDir <- file.path(scriptDir, "models")
  dataDir <- file.path(scriptDir, "data")
  outDir <- file.path(scriptDir, "deliv", modelName)
  delivDir <- file.path(scriptDir, "deliv", modelName)
  dir.create(delivDir)
  file <- file.path(modelDir, modelName, paste0(modelName, ".stan"))
  mod <- cmdstan_model(file)
  return(list(data = data, mod = mod, delivDir = delivDir)) 
}
println <- function(msg) cat(msg); cat("\n")
printf <- function(pattern, ...) println(sprintf(pattern, ...))
source(file.path("tools", "cmdStanTools.r"))
source(file.path("tools", "sbcTools.r"))
c_light <- c("#DCBCBC")
c_light_highlight <- c("#C79999")
c_mid <- c("#B97C7C")
c_mid_highlight <- c("#A25050")
c_dark <- c("#8F2727")
c_dark_highlight <- c("#7C0000")

c_light_trans <- c("#DCBCBC80")
c_light_highlight_trans <- c("#C7999980")
c_mid_trans <- c("#B97C7C80")
c_mid_highlight_trans <- c("#A2505080")
c_dark_trans <- c("#8F272780")
c_dark_highlight_trans <- c("#7C000080")

c_light_teal="#6B8E8E"
c_mid_teal="#487575"
c_dark_teal="#1D4F4F"

c_green_trans <- c("#00FF0080")
c_superfine <- c("#8F272705")
```

1. prior parameter
```{r}
dataName <- "disease_data_20.r"
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_sd1_20"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)

data$alpha_mu_prior <- 0
data$alpha_sd_prior <-1
data$rho_mu_prior <- 0
data$rho_sd_prior <- 1
N = 10 # num of sim and fit
L = 297 # num of posterior draw
sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
```

getting the empirical mean of alpha and rho.
```{r}
modelName <- "dm_n"
submodelName <- "dm_mehat_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)
nChains <- 4
num_cores <- min(nChains, detectCores())

fit <- mod$sample(
  data = data, num_chains = nChains, num_cores = num_cores,
  iter_warmup = 500, iter_sampling = 500, seed = 123,
  adapt_delta = 0.99)
sum <- fit$summary()
me_alpha <- sum %>% filter(str_detect(variable, "alpha")) %>% pull(mean)
me_rho <- sum %>% filter(str_detect(variable, "rho")) %>% pull(mean)
```

```{r}
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_me_sd1_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)
data$alpha_mu_prior <- me_alpha
data$alpha_sd_prior <-1
data$rho_mu_prior <- me_rho
data$rho_sd_prior <- 1
N = 30# num of sim and fit
L = 297 # num of posterior draw
res <- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(res, submodelName, data)
uniformity.sbc(res, submodelName)
plot.sbc(res, submodelName) 
```

```{r}
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_m0_sd1_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)

data$alpha_mu_prior <- 0
data$alpha_sd_prior <- 1
data$rho_mu_prior <- 0
data$rho_sd_prior <-  1
N = 20 # num of sim and fit
L = 297 # num of posterior draw
res_me_sd1_20 <- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(res_me_sd1_20,submodelName, data)
```
 
```{r}
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_m0_sddot1_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)

data$alpha_mu_prior <- 0
data$alpha_sd_prior <- 0.1
data$rho_mu_prior <- 0
data$rho_sd_prior <-  0.1
N = 30 # num of sim and fit
L = 297 # num of posterior draw
res_me_sddot1_20 <- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(res_me_sddot1_20,submodelName, data)
```

```{r}
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_m0_sddot01_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)

data$alpha_mu_prior <- 0
data$alpha_sd_prior <-0.01
data$rho_mu_prior <- 0
data$rho_sd_prior <- 0.01
N = 30 # num of sim and fit
L = 297 # num of posterior draw
res_m0_sddot01_20<- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(res_me_sddot01_20,submodelName, data)

```

```{r}
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_me_sddot01_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)

data$alpha_mu_prior <- me_alpha
data$alpha_sd_prior <-0.01
data$rho_mu_prior <- me_rho
data$rho_sd_prior <- 0.01
N = 30 # num of sim and fit
L = 297 # num of posterior draw
res_me_sddot01_20<- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(res_me_sddot01_20,submodelName, data)

```

```{r}
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_me_sddot01_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)

data$alpha_mu_prior <- me_alpha
data$alpha_sd_prior <-0.01
data$rho_mu_prior <- me_rho
data$rho_sd_prior <- 0.01
N = 1000 # num of sim and fit
L = 297 # num of posterior draw
res<- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(res,submodelName, data)
uniformity.sbc(res, submodelName)
plot.sbc(res, submodelName)
```


```{r}
modelName <- "dm_ela_sbc_n"
submodelName <- "dm_ela_n_me_sddot01_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)

data$alpha_mu_prior <-me_alpha
data$alpha_sd_prior <- 0.01
data$rho_mu_prior <- me_rho
data$rho_sd_prior <- 0.01
N = 1000 # num of sim and fit
L = 297 # num of posterior draw
sbc_res_me_dot01<- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(sbc_res_me_dot01,submodelName, data)
uniformity.sbc(sbc_res_me_dot01, submodelName)
plot.sbc(sbc_res_me_dot01, submodelName)
```

```{r}
submodelName <- "disease_map_ela_sbc_n_dot05"
res <- set_Data_Model_Dir(dataName, modelName)
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)

data$alpha_mu_prior <- me_alpha
data$alpha_sd_prior <- 0.05
data$rho_mu_prior <- me_rho
data$rho_sd_prior <- 0.05
N = 1000 # num of sim and fit
L = 297 # num of posterior draw
sbc_res_me_sddot05<- sbc_new(mod, submodelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(sbc_res_me_sddot05,submodelName, data)
uniformity.sbc(sbc_res_me_sddot05, submodelName)
plot.sbc(sbc_res_me_sddot05, submodelName)
```
 
2. Prior shape 
Shape of the prior affects the generated data and therefore affect SBC greatly. Here, posterior mean were learned and plugged in.

```{r}
modelName <- "dm_ela_sbc_invg"
submodelName <- "dm_ela_sbc_invg_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)
# same first and second moment with normal prior with best sbc
#b/(a-1) = 0.7, b^2/(a-1)^2(a-2) =0.05 (a = 59/5 b= 189/25)
#a/b = 2.2, b^2/(a-1)^2 =0.05 (a =494/5 b= 5379/25)
data$alpha_mu_prior <- me_alpha
data$alpha_sd_prior <- 0.01
data$rho_mu_prior <- me_rho
data$rho_sd_prior <- 0.01

#mean = data$alpha_mu_prior * sq(2/3.14) = 0.42 . 1.1
#var =  data$alpha_sd_prior^2 * (1-2/3.14) = 3.6e-05,  3.6e-05
data$alpha_location_prior <-4902
data$alpha_scale_prior <-  102921/50
data$rho_location_prior <- 302518/9
data$rho_scale_prior <- 3327599/90
N = 1000 
L = 297 
sbc_res_me_sddot01_invg<- sbc_new(mod, modelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(sbc_res_me_sddot01_invg, submodelName, data)
uniformity.sbc(sbc_res_me_sddot01_invg, submodelName)
plot.sbc(sbc_res_me_sddot01_invg, submodelName)
```

```{r}
modelName <- "dm_ela_sbc_t"
submodelName <- "dm_ela_sbc_t_20"
dataName <- "disease_data_20.r"
res <- set_Data_Model_Dir(dataName, modelName)
data <- res$data
mod <- res$mod
delivDir <- file.path(scriptDir, "deliv", submodelName)
dir.create(delivDir)
# same first and second moment with normal prior with best sbc
data$alpha_location_prior <- 0.52
data$alpha_scale_prior <- 0.01
data$rho_location_prior <- 1.4
data$rho_scale_prior <- 0.01
N = 1000 
L = 297 
sbc_res_me_sddot01_t<- sbc_new(mod, modelName, data = data, N = N, L = L, save_progress = delivDir)
ppc.sbc(sbc_res_me_sddot01_t, submodelName, data)
uniformity.sbc(sbc_res_me_sddot01_t, submodelName)
plot.sbc(sbc_res_me_sddot01_t, submodelName)
```

3. likelihood
```{r}
submodelName <- "bernoulli_disease_map"
data$alpha_mu_prior <- 0
data$alpha_sd_prior <- 1
data$rho_mu_prior <- 0
data$rho_sd_prior <- 1
N = 10 #(bins = 20)*N # num of sim and fit
M = 597 # 897 (6n -3) # num of post. draw - related to iter_sampling - not used currently

res = set_Data_Model_Dir(dataName, modelName)
data = res$data
mod = res$mod
delivDir = res$delivDir

sbc_res_me_sd1<- sbc_new(mod, submodelName, data = data, N = N, M = M, save_progress = delivDir)
ppc.sbc(sbc_res_me_sd1)
uniformity.sbc(sbc_res_me_sd1)
plot.sbc(sbc_res_me_sd1)
```


